
GET http://localhost:3000/api/tweets/ HTTP/1.1

###

GET http://localhost:3000/api/tweets/user/5ce38abc994d499ab881420d HTTP/1.1


###

//5ce1b529d20f444cb8eb1061  12
//5ce1b588e924e8050cef45fc thanh
//5ce1b76ce7d23839ec53cfed test1

POST http://localhost:3000/api/tweets
content-type: application/json

{
  "content":"this is 2nd tweet",
  "createdUser":{"user":"5ce1b76ce7d23839ec53cfed"},
  "comments":[{"user":"5ce1b529d20f444cb8eb1061","comment":"that's good","likes":["5ce1b529d20f444cb8eb1061"]},
    {"user":"5ce1b588e924e8050cef45fc","comment":"yep","likes":["5ce1b588e924e8050cef45fc"]}],
  "likes":[{"user":"5ce1b588e924e8050cef45fc"},{"user":"5ce1b529d20f444cb8eb1061"}],
  "retweets":[{"user":"5ce1b588e924e8050cef45fc"},{"user":"5ce1b529d20f444cb8eb1061"}]
}

###
DELETE http://localhost:3000/api/tweets/5ce38abc994d499ab881420d HTTP/1.1

###

PUT http://localhost:3000/api/tweets/5ce38aff994d499ab8814214
content-type: application/json

{
  "content":"this is my 1st tweet"
}

###
PUT http://localhost:3000/api/tweets/5ce38aff994d499ab8814214/like/
content-type: application/json

{
  "user":"5ce1b76ce7d23839ec53cfed"
}

###
DELETE http://localhost:3000/api/tweets/5ce38aff994d499ab8814214/like/
content-type: application/json

{
  "user":"5ce1b588e924e8050cef45fc"
}

###
PUT http://localhost:3000/api/tweets/5ce38aff994d499ab8814214/comment HTTP/1.1
Content-Type: application/json

{
  "user":"5ce1b588e924e8050cef45fc",
  "comment":"cool story bro",
  "likes":[]
}

###
DELETE http://localhost:3000/api/tweets/5ce38aff994d499ab8814214/comment/5ce38aff994d499ab8814216 HTTP/1.1

###


PUT http://localhost:3000/api/tweets/5ce38aff994d499ab8814214/comment/5ce38bf8994d499ab881421d/like
content-type: application/json

{
  "user":"5ce1b588e924e8050cef45fc"
}

###

DELETE  http://localhost:3000/api/tweets/5ce38aff994d499ab8814214/comment/5ce38bf8994d499ab881421d/like
content-type: application/json

{
  "user":"5ce1b588e924e8050cef45fc"
}




###
GET http://localhost:3000/api/tweets/5ce1b76ce7d23839ec53cfed/stats HTTP/1.1

###
GET http://localhost:3000/api/tweets/5ce38e4b1417c94298b1eaa4/


//until this

//USER TESTING STARTED FROM HERE >>>>>>>>>>>

###
GET http://localhost:3000/api/users HTTP/1.1
###

POST http://localhost:3000/api/users/5ce1b76ce7d23839ec53cfed/follow HTTP/1.1
content-type: application/json

{
  "user":"5ce1b588e924e8050cef45fc"
}
###

DELETE http://localhost:3000/api/users/5ce1b76ce7d23839ec53cfed/follow HTTP/1.1
content-type: application/json

{
  "user":"5ce1b588e924e8050cef45fc"
}


###
GET http://localhost:3000/api/users/5ce1b76ce7d23839ec53cfed


###
GET http://localhost:3000/api/users/search/than